---
- name: backup cau hinh
  hosts: Router
  gather_facts: no

  tasks:
    - name: backup config
      ios_config:
        backup: yes
      register: config_output

    - name: rename
      copy:
        src: "{{config_output.backup_path}}"
        dest: "./backup/Router.config"

    - name: remove non-config lines
      lineinfile:
        path: "./backup/Router.config"
        line: "Building configuration..."
        state: absent

    - name: remove non-config lines regex
      lineinfile:
        path: "./backup/Router.config"
        regex: 'Current configuration.*'
        state: absent
