---
- name: tao vlan
  hosts: all
  gather_facts: no

  tasks:
    - name: Create vlan
      ios_vlan:
        vlan_id: "{{ item.number }}"
        name: "{{ item.name }}"
        state: present
      with_items:
        - { number: 60, name: "phong_60" }
        - { number: 61, name: "phong_61" }
        - { number: 62, name: "phong_62" }

    - name: Show vlan
      ios_command:
        commands:
          - show vlan
      register: show_vlan

    - debug: var=show_vlan.stdout_lines
